<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [51]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    if len(A[0]) != len(B):
        return ("These matrices can't be multiplied!!")
    else:
        result = [[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]
    return result

In [53]:
# Program to multiply two matrices using list comprehension

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

matrix_mul(X,Y)

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [99]:
from random import uniform
import numpy as np
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    index = 0
    normalized = [i/sum(A) for i in A]
    cumsum_list = np.cumsum(normalized)  
    random = uniform(0.0,1.0)
   # print(random)
    for i in range(0,len(cumsum_list)):
       # print("cumsum is {}".format(cumsum_list[i]))
        if (random < cumsum_list[i]):
            output = A[i]
            #print ("output is {}".format(output))
            break
    return output#selected_random_number

def sampling_based_on_magnitued(A):
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued([0, 5, 27, 6, 13, 28, 100, 45, 10, 200])

200
200
200
200
200
200
200
200
200
200
100
100
100
27
45
200
27
28
27
100
200
27
100
100
200
200
200
100
100
28
200
45
100
45
100
13
28
200
200
100
27
100
100
200
100
200
100
45
45
6
200
28
100
200
45
10
200
200
200
200
200
100
200
45
200
100
200
100
200
100
45
200
28
200
200
28
200
200
45
200
100
100
100
100
200
200
13
28
200
100
10
200
100
200
200
27
100
28
100


AttributeError: 'NoneType' object has no attribute 'value_counts'

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [116]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    output = "#" * len(re.sub(r'\D', '', String))
    return(output) # modified string which is after replacing the # with digits

replace_digits("#2a$#b%c%561#")

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student6 43
student1 45
student7 47
student5 48
</pre>

In [158]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    student_Score = {}
    for student,mark in zip(Students,Marks):
        student_Score.update({student:mark})
    # write code for computing top top 5 students
    top_5_students = {k: v for k, v in sorted(kamus.items(), key=lambda item: item[1],reverse=True)[:5]}
    # write code for computing top least 5 students
    least_5_students = {k: v for k, v in sorted(kamus.items(), key=lambda item: item[1])[:5]}
    # write code for computing top least 5 students
    n = len(Marks)
    first_quartile = int(n/4) if (n/4).is_integer() else int(n/4)+1
    third_quartile = int(3*n/4) if (3*n/4).is_integer() else int(3*n/4)+1  # as we want <75th percentile
    students_within_25_and_75 = {k: v for k, v in sorted(kamus.items(), key=lambda item: item[1],reverse=True)[first_quartile:third_quartile-1]}
# compute this
    
    return top_5_students, least_5_students, students_within_25_and_75


Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
print("Top 5 students are: {} \nLeast 5 students are: {}\nStudents within 25 and 75 are: {}".format(top_5_students, least_5_students, students_within_25_and_75))

Top 5 students are: {'student8': 98, 'student10': 80, 'student2': 78, 'student5': 48, 'student7': 47} 
Least 5 students are: {'student3': 12, 'student4': 14, 'student9': 35, 'student6': 43, 'student1': 45}
Students within 25 and 75 are: {'student5': 48, 'student7': 47, 'student1': 45, 'student6': 43, 'student9': 35}


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [41]:
import math
import numpy


# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2

def closest_points_to_p(S, P):
    # write your code here
    cosine_distance = {}
    for points in S:
        distance = (np.dot(points,P)/(np.dot(points,points)*np.dot(P,P))**(0.5))
        cosine_distance.update({points:1-distance})
    return cosine_distance  # its list of tuples



S = [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P = (3,-4)
points = closest_points_to_p(S, P)
top5_closest = {k: v for k, v in sorted(points.items(), key=lambda item: item[1])[:5]}

top5_closest
for (key,value) in top5_closest:
 
    print((key,value)) #print the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [101]:
import regex as re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# source: https://stackoverflow.com/questions/56948506/how-to-extract-coefficients-from-a-line-equation-in-python-without-using-numpy
def CoefficientIntercept(equation):
    coef_x = re.findall('-?[0-9.]*[Xx]', equation)[0][:-1]
    coef_y = re.findall('-?[0-9.]*[Yy]', equation)[0][:-1]
    intercept = re.sub("[+-]?\d+[XxYy]|[+-]?\d+\.\d+[XxYy]","", equation)    
    return float(coef_x), float(coef_y), float(intercept)

# written to handle where the points on the line
def PointLiesOnLine(Xeq,Yeq,Aeq,Beq,Ceq):
    if ((Aeq*Xeq)+(Beq*Yeq)+Ceq) == 0:
        return True
    else:
        return False
    

# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    A,B,C = CoefficientIntercept(line)
    redCalc,blueCalc = [],[]
    output = ""

    for pointA,pointB in zip(red,blue):
        xRed,yRed = pointA
        xBlue,yBlue = pointB
    
        if PointLiesOnLine(xRed,yRed,A,B,C) or PointLiesOnLine(xBlue,yBlue,A,B,C):
            output = "NO"
            break;
        else:
            #redCalc.append(yRed-((A*xRed)+C)/(-B))
            #blueCalc.append(yBlue-((A*xBlue)+C)/(-B))
            
            #the distance between a point and a line 
            redCalc.append(((A*xRed) + (B*yRed) + C)/math.sqrt(A**2+B**2))
            blueCalc.append(((A*xBlue) + (B*yBlue) + C)/math.sqrt(A**2+B**2))

    if (np.sum(np.sign(redCalc)) == 5 or np.sum(np.sign(redCalc)) == -5) and (np.sum(np.sign(blueCalc)) == 5 or np.sum(np.sign(blueCalc)) == -5):
        output = "YES"
    else:
        output = "NO"
    return output #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    return #list of values

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(# print above values)

In [146]:
# source: 
def replace(string):
    lst=string.split(',')
    for i in range(len(lst)):
        if lst[i].isdigit():
            for j in range(i+1):
                lst[j]=int(lst[i])//(i+1)
            new_index=i
            new_value=int(lst[i])
            break
    for i in range(new_index+1,len(lst)):
        if lst[i].isdigit():
            replacement=(new_value+int(lst[i]))//(i-new_index+1)
            for j in range(new_index,i+1):
                lst[j]=replacement
            new_index=i
            new_value=int(lst[i])
    try:
        for i in range(new_index+1,len(lst)):
            if not(lst[i].isdigit()):
                count=lst.count('_')
                break
        replacement_2=new_value//(count+1)
        for i in range(new_index,len(lst)):
            lst[i]=replacement_2
    except:
        pass
    return lst 

replace("_,20,30,_,_,_,40,50,_,_")

[10, 20, 12, 12, 12, 12, 31, 10, 10, 10]

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [162]:
A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


dictionary1 = {
'F1S1': 0,
'F2S1': 0,
'F3S1': 0,
'F4S1': 0,
'F5S1': 0,
'F1S2': 0,
'F2S2': 0,
'F3S2': 0,
'F4S2': 0,
'F5S2': 0,
'F1S3': 0,
'F2S3': 0,
'F3S3': 0,
'F4S3': 0,
'F5S3': 0,
}

dictionary2 = {
'S1': 0,
'S2': 0,
'S3': 0
}


def compute_conditional_probabilites(A):
    for i in range(len(A)):
        k = A[i][0] + A[i][1]
        dictionary1[k] += 1
        y = A[i][1]
        dictionary2[A[i][1]] += 1

compute_conditional_probabilites(A)

print('Probability of P(F=F1|S==S1)', (dictionary1['F1S1']/dictionary2['S1']))
print('Probability of P(F=F2|S==S1)', (dictionary1['F2S1']/dictionary2['S1']))
print('Probability of P(F=F3|S==S1)', (dictionary1['F3S1']/dictionary2['S1']))
print('Probability of P(F=F4|S==S1)', (dictionary1['F4S1']/dictionary2['S1']))
print('Probability of P(F=F5|S==S1)', (dictionary1['F5S1']/dictionary2['S1']))

print('Probability of P(F=F1|S==S2)', (dictionary1['F1S2']/dictionary2['S2']))
print('Probability of P(F=F2|S==S2)', (dictionary1['F2S2']/dictionary2['S2']))
print('Probability of P(F=F3|S==S2)', (dictionary1['F3S2']/dictionary2['S2']))
print('Probability of P(F=F4|S==S2)', (dictionary1['F4S2']/dictionary2['S2']))
print('Probability of P(F=F5|S==S2)', (dictionary1['F5S2']/dictionary2['S2']))

print('Probability of P(F=F1|S==S3)', (dictionary1['F1S3']/dictionary2['S3']))
print('Probability of P(F=F2|S==S3)', (dictionary1['F2S3']/dictionary2['S3']))
print('Probability of P(F=F3|S==S3)', (dictionary1['F3S3']/dictionary2['S3']))
print('Probability of P(F=F4|S==S3)', (dictionary1['F4S3']/dictionary2['S3']))
print('Probability of P(F=F5|S==S3)', (dictionary1['F5S3']/dictionary2['S3']))

Probability of P(F=F1|S==S1) 0.25
Probability of P(F=F2|S==S1) 0.25
Probability of P(F=F3|S==S1) 0.0
Probability of P(F=F4|S==S1) 0.25
Probability of P(F=F5|S==S1) 0.25
Probability of P(F=F1|S==S2) 0.3333333333333333
Probability of P(F=F2|S==S2) 0.3333333333333333
Probability of P(F=F3|S==S2) 0.3333333333333333
Probability of P(F=F4|S==S2) 0.0
Probability of P(F=F5|S==S2) 0.0
Probability of P(F=F1|S==S3) 0.0
Probability of P(F=F2|S==S3) 0.3333333333333333
Probability of P(F=F3|S==S3) 0.3333333333333333
Probability of P(F=F4|S==S3) 0.3333333333333333
Probability of P(F=F5|S==S3) 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [191]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    b = []
    c = []
    a = []
    list_S1 = S1.split()
    list_S2 = S2.split()
    for i in list_S1:
        if i not in list_S2:
            b.append(i)
        elif i in list_S2:
            a.append(i)

    for i in list_S2:
        if i not in list_S1:
            c.append(i)
    return a,b,c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c= string_features(S1, S2)
print(a,b,c)

['the', 'column', 'will', 'contain', 'only', 'uniques', 'values'] ['first', 'F', '5'] ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [194]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    result = 0
    for y,yscore in A:
        result += (y*math.log10(yscore))+((1-y)*math.log10(1-yscore))
    loss = -1/(len(A))*result
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
